
# should be autogenerated when building/installing package

## pathes to required binaries
VOSBIN="/usr/sbin/vos"
RXDEBUGBIN="/usr/sbin/rxdebug"
UDEBUGBIN="/usr/sbin/udebug"
FSBIN="/usr/bin/fs"
OSDBIN="osd"
BOSBIN="/usr/sbin/bos"
TOKENBIN="/usr/bin/tokens"
AKLOGBIN="/usr/bin/aklog"
KINITBIN="/usr/bin/kinit"
KLISTBIN="/usr/bin/klist"
KDESTROYBIN="/usr/lib/mit/bin/kdestroy"
DIGBIN="/usr/bin/dig"
